import { describe, it, expect, beforeEach } from '@jest/globals';
import jwt from 'jsonwebtoken';
import { createSignedPath, verifySignedPath } from '../../src/utils/presigned-url';

describe('Testing signed URL utilities', () => {
  beforeEach(() => {
    process.env.SELF_SIGNING_SECRET = 'test-secret';
  });

  describe('createSignedPath', () => {
    it('should append token as query parameter to a plain path', () => {
      const result = createSignedPath('/files/myfile.csv');
      expect(result).toMatch(/^\/files\/myfile\.csv\?token=.+$/);
    });

    it('should append token with & if path already has query parameters', () => {
      const result = createSignedPath('/files/myfile.csv?foo=bar');
      expect(result).toMatch(/^\/files\/myfile\.csv\?foo=bar&token=.+$/);
    });

    it('should throw if SELF_SIGNING_SECRET is not set', () => {
      delete process.env.SELF_SIGNING_SECRET;
      expect(() => createSignedPath('/files/myfile.csv')).toThrow('Missing environment variable: SELF_SIGNING_SECRET');
    });
  });

  describe('verifySignedPath', () => {
    it('should return true for a valid token generated by createSignedPath', () => {
      const filePath = '/files/myfile.csv';
      const signedUrl = createSignedPath(filePath);
      const token = new URL(signedUrl, 'http://localhost').searchParams.get('token')!;
      expect(() => verifySignedPath(filePath, token)).not.toThrow();
    });

    it('should throw 401 if token is for a different file', () => {
      const signedUrl = createSignedPath('/files/myfile.csv');
      const token = new URL(signedUrl, 'http://localhost').searchParams.get('token')!;
      expect(() => verifySignedPath('/files/otherfile.csv', token)).toThrow(expect.objectContaining({ message: 'Invalid download token' }));
    });

    it('should throw 410 if token is expired', () => {
      const token = jwt.sign({ filePath: '/files/myfile.csv' }, process.env.SELF_SIGNING_SECRET!, {
        expiresIn: -1, // already expired
        algorithm: 'HS256',
      });
      expect(() => verifySignedPath('/files/myfile.csv', token)).toThrow(expect.objectContaining({ message: 'Download link has expired' }));
    });

    it('should throw 401 if token is tampered with', () => {
      expect(() => verifySignedPath('/files/myfile.csv', 'this.is.not.a.valid.token')).toThrow(
        expect.objectContaining({ message: 'Invalid download token' }),
      );
    });

    it('should throw if SELF_SIGNING_SECRET is not set', () => {
      const signedUrl = createSignedPath('/files/myfile.csv');
      const token = new URL(signedUrl, 'http://localhost').searchParams.get('token')!;
      delete process.env.SELF_SIGNING_SECRET;
      expect(() => verifySignedPath('/files/myfile.csv', token)).toThrow('Missing environment variable: SELF_SIGNING_SECRET');
    });
  });
});
