name: soilhive-core
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest@sha256:20e96e40e673ffa474ac4da56c91cb0adba28b8571bd274ce255e6120265c1f4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgis:5432/database
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgis
    command: start-dev

  postgis:
    image: postgis/postgis:18-3.6@sha256:f248a10d133f63d01aefab324f3462d7e1002e9cc1b65c6585626f6cb7a3d85c
    platform: linux/amd64    
    command: ["postgres", "-c", "postgis.gdal_enabled_drivers=ENABLE_ALL"]
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgis_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgis_data:
