name: soilhive-core
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgis:5432/database
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgis
    command: start-dev

  postgis:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:latest
    environment:
      SERVICES: s3
      DEBUG: "1"
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://dbuser:dbpass@postgis:5432/database
      LOCALSTACK_ENDPOINT: http://localstack:4566
    ports:
      - "3001:3001"
    depends_on:
      - postgis
      - localstack

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: npm start

volumes:
  postgis_data:
  localstack_data:
