name: soilhive-core
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest@sha256:9b0330756022422149aa6502eb2def8cd47c6e1b000c7c65cdb13e7c0133e992
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgis:5432/database
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgis
    command: start-dev

  postgis:
    image: postgis/postgis:18-3.6@sha256:c48eb5172cfb005ee094a522fe69f27f1ee9e184ba649fe068520a597fa30409
    platform: linux/amd64    
    command: ["postgres", "-c", "postgis.gdal_enabled_drivers=ENABLE_ALL"]
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgis_data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  postgis_data:
