name: soilhive-core
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest@sha256:dea26401d06341095cc4ea9d66896200b55de5ca1daa1d2fcbe58493afa6e0ad
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgis:5432/database
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgis
    command: start-dev

  postgis:
    image: postgis/postgis:18-3.6@sha256:4de7017b328c47b337ea86eb17277c45c5b05b8378924112972e79d60803b935
    platform: linux/amd64
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgis_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  localstack:
    image: localstack/localstack:latest@sha256:84c352d577e0e4f461f232416e3e5f5c51eb65ba9b299a7530e5e2f42b58dbad
    environment:
      SERVICES: s3
      DEBUG: "1"
    ports:
      - "4566:4566"
      - "4571:4571"
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgis_data:
  localstack_data:
