name: soilhive-core
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest@sha256:5fdbf2dbb5897cc34e82de49d13e23db011f9925089dbc555fc095f2c8bc1dac
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin_password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgis:5432/database
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgis
    command: start-dev

  postgis:
    image: postgis/postgis:18-3.6@sha256:1ac8d723bbf66159010056348cb54f521a8ee4c83d8df7ccec0c103ca004c0b8
    platform: linux/amd64
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgis_data:/var/lib/postgresql
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOST: postgis
      POSTGRES_PORT: 5432
      POSTGRES_DB: database
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_SCHEMA: soilhive
    ports:
      - "4001:3000"
    depends_on:
      - postgis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      PORT: 80
      BACKEND_BASE_URL: http://localhost:4001/api/v1
    ports:
      - "80:80"
    stdin_open: true
    tty: true

volumes:
  postgis_data:
