import { Column, Entity, PrimaryColumn } from 'typeorm';
import { DataRequestStatus } from '../types/enums';

/**
 * One data request and the outcome its Run reached (docs/adr/0037).
 *
 * Deliberately not a BaseTable, and not because two of its columns are merely unused:
 *  - `@CreateDateColumn` is generated by TypeORM on insert and overrides what it is given, but
 *    `created_at` here is the *submission* time, copied from the job. The row is written when the
 *    Run terminates, so inheriting would set it to roughly `completed_at` and lose the only
 *    record of when the request was made.
 *  - `@DeleteDateColumn` would put a soft delete within reach of a record whose deletion is the
 *    whole erasure path for a payload nobody owns — leaving the bytes on disk while reads
 *    pretend they are gone.
 *  - `updated_at` could never carry information: the row is written once and never updated.
 *  - BaseTable's columns are `timestamp`; these are `timestamptz`, because they are copied from
 *    pg-boss's own timestamptz columns and truncating the offset would be a lossy copy.
 *
 * Three properties of a row that the type cannot carry:
 *  - **Append-only, never deduplicated.** An identical `request` inserts a new row. Sharing
 *    one across callers would hand one caller's payload — computed under their entitlements
 *    — to another; Filters can dedupe (docs/adr/0007) only because they dedupe per owner,
 *    and there is no owner here to scope it to.
 *  - **The id is a bearer capability, and it is the Run's id.** With no owner column, holding
 *    the id is the whole of the permission to read `data` *and to destroy the row*. It is
 *    never generated here: it is the id of the pg-boss job that ran it, so one identifier
 *    addresses the request while the job lives and this row afterwards. pg-boss generates it
 *    with gen_random_uuid() — 122 unstructured random bits — rather than the uuidv7() the
 *    rest of this schema uses, which is exactly the property the capability rests on.
 *  - **A cancelled Run writes nothing.** Cancelling is how a Data Request is destroyed, so
 *    `status` has two values and the absence of a row is how a cancellation reads.
 *
 * `data` holds the payload inline and is unbounded, so a find() pays for all of it.
 */
@Entity('data_requests')
export default class DataRequestEntity {
  /** The Run's id: the pg-boss job id, supplied on insert and never defaulted. */
  @PrimaryColumn('uuid')
  id: string;

  @Column('text', { nullable: false })
  status: DataRequestStatus.COMPLETED | DataRequestStatus.FAILED;

  /**
   * What was asked, plus what resolving it produced — `units`, `derived_filter_id`,
   * `unit_count`. The resolved half is not a convenience: `unit_id` in the payload is a
   * UserGeometry uuid, so without the units' labels and areas a row that outlives its job
   * is a table of identifiers nobody can interpret.
   *
   * Never carries `created_by`, `isDataAdmin` or `isSuperAdmin` — it is returned verbatim,
   * and this row has no owner to scope a leak to.
   */
  @Column('jsonb', { nullable: false })
  request: object;

  /** The answer. Null exactly when the Run failed; the table's CHECK pins the pairing. */
  @Column('jsonb', { nullable: true })
  data: object | null;

  /** Display-ready failure copy, already translated. Null on success. */
  @Column('text', { nullable: true })
  message: string | null;

  /** Copied from the job: when the Run was submitted, not when this row was written. */
  @Column('timestamptz', { nullable: false })
  created_at: Date;

  /** When the Run reached its outcome. */
  @Column('timestamptz', { nullable: false })
  completed_at: Date;
}
