name: NodeJS

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch: {}


permissions:
  contents: read
  pull-requests: read

jobs:

  nodejs-frontend:
    name: Node.js CI
    uses: varda-ag/.github/.github/workflows/nodejs.yaml@bf80d0c0e30b15a047dacd693bec8f5bfda03b67 # v1.13.3
    with:
      node-version: '24'
      project-path: './frontend'
      disable-lint: true
      disable-unit-tests: true
      disable-unit-tests-coverage: true
      disable-integration-tests: true
      disable-integration-tests-coverage: true
      disable-e2e-tests: true
      disable-e2e-tests-coverage: true

  nodejs-backend:
    name: Node.js CI
    uses: varda-ag/.github/.github/workflows/nodejs.yaml@bf80d0c0e30b15a047dacd693bec8f5bfda03b67 # v1.13.3
    with:
      node-version: '24'
      project-path: './backend'
      disable-lint: true
      disable-unit-tests: true
      disable-unit-tests-coverage: true
      disable-integration-tests: true
      disable-integration-tests-coverage: true
      disable-e2e-tests: true
      disable-e2e-tests-coverage: true
      # TODO: use pnpm instead of npm
      use-npm: true
      use-pnpm: false

