name: PR Validation

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: read

jobs:

  nodejs-frontend:
    name: Node.js CI
    uses: varda-ag/.github/.github/workflows/nodejs.yaml@main
    with:
      node-version: '18.x'
      project-path: './frontend'
      disable-lint: true
      disable-unit-tests: true
      disable-unit-tests-coverage: true
      disable-integration-tests: true
      disable-integration-tests-coverage: true
      disable-e2e-tests: true
      disable-e2e-tests-coverage: true

  nodejs-backend:
    name: Node.js CI
    uses: varda-ag/.github/.github/workflows/nodejs.yaml@main
    with:
      node-version: '18.x'
      project-path: './backend'
      disable-lint: true
      disable-unit-tests: true
      disable-unit-tests-coverage: true
      disable-integration-tests: true
      disable-integration-tests-coverage: true
      disable-e2e-tests: true
      disable-e2e-tests-coverage: true

  commitlint:
    name: Commitlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      
      - name: Configure commitlint
        run: |
          echo "export default { extends: ['@commitlint/config-conventional'] };" > commitlint.config.js

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose | tee commitlint-output.txt

      - name: Add summary
        run: |
          cat commitlint-output.txt >> $GITHUB_STEP_SUMMARY

  docker-build-frontend:
    name: Docker Build
    needs:
      - nodejs-frontend
    uses: varda-ag/.github/.github/workflows/docker-build.yaml@main
    with:
      imageName: soilhive-core-frontend
      context: frontend
      push: true
      imageVersion: pr-${{ github.event.pull_request.number }}-${{ github.sha }}

    permissions:
      contents: read
      packages: write
      id-token: write

  docker-build-backend:
    name: Docker Build
    needs:
      - nodejs-backend
    uses: varda-ag/.github/.github/workflows/docker-build.yaml@main
    with:
      imageName: soilhive-core-backend
      context: backend
      push: true
      imageVersion: pr-${{ github.event.pull_request.number }}-${{ github.sha }}

    permissions:
      contents: read
      packages: write
      id-token: write
