name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: write

jobs:

  nodejs-frontend:
    name: Node.js CI
    uses: varda-ag/.github/.github/workflows/nodejs.yaml@main
    with:
      node-version: '18.x'
      project-path: './frontend'
      disable-lint: true
      disable-unit-tests: true
      disable-unit-tests-coverage: true
      disable-integration-tests: true
      disable-integration-tests-coverage: true
      disable-e2e-tests: true
      disable-e2e-tests-coverage: true

  nodejs-backend:
    name: Node.js CI
    uses: varda-ag/.github/.github/workflows/nodejs.yaml@main
    with:
      node-version: '18.x'
      project-path: './backend'
      disable-lint: true
      disable-unit-tests: true
      disable-unit-tests-coverage: true
      disable-integration-tests: true
      disable-integration-tests-coverage: true
      disable-e2e-tests: true
      disable-e2e-tests-coverage: true

  version:
    name: version
    runs-on: ubuntu-latest

    needs:
      - nodejs-frontend
      - nodejs-backend

    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.VARDA_VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VARDA_VERSION_BUMPER_PRIVATE_KEY }}
          permission-contents: write

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765 # v6
        id: changelog
        with:
          skip-git-pull: true
          skip-on-empty: true
          preset: conventionalcommits
          skip-commit: true
          skip-tag: true
          skip-version-file: true

  build-push-docker-frontend:
    uses: varda-ag/.github/.github/workflows/docker-build.yaml@main
    needs:
      - version
    with:
      context: frontend
      imageName: soilhive-core-frontend
      imageVersion: ${{ needs.version.outputs.tag }}
      push: true
    permissions:
      contents: read
      packages: write
      id-token: write   # This is required for requesting the JWT token from OIDC

  build-push-docker-backend:
    uses: varda-ag/.github/.github/workflows/docker-build.yaml@main
    needs:
      - version
    with:
      context: backend
      imageName: soilhive-core-backend
      imageVersion: ${{ needs.version.outputs.tag }}
      push: true
    permissions:
      contents: read
      packages: write
      id-token: write   # This is required for requesting the JWT token from OIDC

  changelog:
    name: Changelog
    runs-on: ubuntu-latest

    needs:
      - build-push-docker-frontend
      - build-push-docker-backend

    outputs:
      tag: ${{ steps.changelog.outputs.tag }}
      clean_changelog: ${{ steps.changelog.outputs.clean_changelog }}
      version: ${{ steps.changelog.outputs.version }}

    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.VARDA_VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VARDA_VERSION_BUMPER_PRIVATE_KEY }}
          permission-contents: write

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Create Changelog
        uses: TriPSs/conventional-changelog-action@67139193614f5b9e8db87da1bd4240922b34d765 # v6
        id: changelog
        with:
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          git-user-name: 'github-actions[bot]'
          git-user-email: 'github-actions[bot]@users.noreply.github.com'
          skip-git-pull: true
          input-file: CHANGELOG.md
          skip-on-empty: true
          create-summary: true
          preset: conventionalcommits
          skip-commit: false

  release:
    name: Release
    needs:
      - changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Create Release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631 # v2
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          generate_release_notes: true
          body: |
            <details>
              <summary>Changelog</summary>

            ${{ needs.changelog.outputs.clean_changelog }}
            </details>