name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  release:
    uses: varda-ag/.github/.github/workflows/release.yaml@main
    with:
      gh-app-id: ${{ vars.VARDA_VERSION_BUMPER_APPID }}
    secrets:
      gh-app-private-key: ${{ secrets.VARDA_VERSION_BUMPER_PRIVATE_KEY }}
    permissions:
      contents: write
      issues: write
      pull-requests: write