name: Renovate
on:
  # Allows manual/automated ad-hoc trigger
  workflow_dispatch:
    inputs:
      log-level:
        description: Override default log level
        required: false
        default: info
        type: choice
        options:
          - info
          - warning
          - debug
  # Enable retry flag on edits to PRs
  pull_request:
    types:
      - edited
      - reopened
      - synchronize
  issues:
    types:
      - edited
      - reopened
  # Run twice in the early morning for initial and follow up steps (create pull request and merge)
  schedule:
    - cron: 30 4,6 * * *

concurrency: renovate
jobs:
  renovate:
    uses: varda-ag/.github/.github/workflows/renovate.yaml@4a354a27c3af07427e493126caf465dff203169b # v1.11.1
    with:
      log-level: ${{ github.event.inputs.log-level || 'info' }}
      gh-app-id: ${{ vars.VARDA_RENOVATE_APP_ID }}
      aws-role-to-assume: ${{ vars.AWS_ROLE_ARN }}
      aws-region: ${{ vars.AWS_REGION }}
    secrets:
      gh-app-private-key: ${{ secrets.VARDA_RENOVATE_PRIVATE_KEY }}
    permissions:
      contents: read
      id-token: write